#-*-coding:utf-8-*-
from com.deppon.nhr.login.login import driver,sleep, loginNhr, menu

loginNhr()
menu()
mainNav3=driver.find_element_by_xpath(u"//div[text()='认证资料库']").click()
print("进入资料库")
sleep(3)
print("选择认证大类")
idenCa=driver.find_element_by_xpath(u"//td[input[@name='identificationkind']]/following-sibling::td/div[1]")
idenCa.click()
caSe=driver.find_element_by_xpath(u"//li[text()='IT类']")
caSe.click()
sleep(1)
print("选择认证层级")
idenLe=driver.find_element_by_xpath(u"//td[input[@name='identificationlevel']]/following-sibling::td/div[1]")
idenLe.click()
leSe=driver.find_element_by_xpath(u"//li[text()='中级']")
leSe.click()
sleep(1)
print("选择条目性质")
idenLe=driver.find_element_by_xpath(u"//td[input[@name='itemproperty']]/following-sibling::td/div[1]")
idenLe.click()
leSe=driver.find_element_by_xpath(u"//li[text()='认证面谈']")
leSe.click()

print("点击新增按钮")
btn=driver.find_element_by_xpath(u"//button[span[text()='新增']]")
btn.click()
print("新增条目")
itemname=driver.find_element_by_xpath(u"//input[@name='itemname']")
itemname.send_keys(u"系统思考1")
print("条目序号")
itemno=driver.find_element_by_xpath(u"//input[@name='itemno']")
itemno.send_keys(u"7")
print("展现层级")
showlevel=driver.find_element_by_xpath(u"//input[@name='showlevel']")
showlevel.send_keys(u"灵活运用")
print("详细描述")
detail=driver.find_element_by_xpath(u"//textarea[@name='detail']")
detail.send_keys(u"这里添加详细描述")
print("展现层级")
caseshow=driver.find_element_by_xpath(u"//textarea[@name='caseshow']")
caseshow.send_keys(u"这里添加问题示列")

print("保存")
btn1=driver.find_element_by_xpath(u"//button[span[text()='保存']]")
btn1.click()
sleep(1)
print("保存成功")
btn1=driver.find_element_by_xpath(u"//button[span[text()='确定']]")
btn1.click()
driver.close()

